Use ParserSettings.forServer instead of ParserSettings.apply
To figure this out I had to run sbt console and try calling
maxContentLength on parser settings, which finally returned a useful
error:

scala> ps.maxContentLength
java.lang.IllegalStateException: Generic ParserSettings were created missing a server/client specific max-content-length setting. Adapt settings in the config file or use ParserSettings.forClient or ParserSetting.forServer instead of ParserSettings.apply / ParserSettings.create.
  at akka.http.impl.settings.ParserSettingsImpl.$anonfun$maxContentLength$1(ParserSettingsImpl.scala:64)
  at scala.Option.getOrElse(Option.scala:189)
  at akka.http.impl.settings.ParserSettingsImpl.maxContentLength(ParserSettingsImpl.scala:64)
  ... 31 elided

Previously, `main` just failed with:

Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: The provided ParserSettings is a generic object that does not contain the server-specific settings.

Searching for this message in the akka source code for ServerSettingsImpl,
you find:

require(
    Try { parserSettings.maxContentLength }.isSuccess,
    "The provided ParserSettings is a generic object that does not contain the server-specific settings."
  )

And that is how I got on track of `parserSettings.maxContentLength`
and tried to call it directly without `Try {}` to see what error it
was throwing, which led me to the error mentioned above.